services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: resume_demo
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      timeout: 20s
      retries: 10
      start_period: 30s
      interval: 10s

  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_SOURCE: "root:123456@tcp(mysql:3306)/resume_demo?charset=utf8mb4&parseTime=True&loc=Local"
    restart: unless-stopped